# to create from scratch: conda env create -f environment.yml
# to update the environment: conda env update --name myenv --file environment.yml --prune
# or update with environment activated: conda env update --file environment.yml --prune

# for exe pyinstaller: install "conda install pywin32" on win machine

name: robots-gis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - compas
  - compas_fab
  - pip
  - compas_rrc
  - pip:
    # code style tools
    - flake8
    - autopep8
    - pylint
    - isort
    # testing tools
    - pytest
    - ironpython-pytest
    # autocomplete for Rhino
    - Rhino-stubs
    - Grasshopper-stubs