joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_2:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_3:
    has_velocity_limits: true
    max_velocity: 4.36332
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_4:
    has_velocity_limits: true
    max_velocity: 7.33038
    has_acceleration_limits: true
    max_acceleration: 1.466076
  joint_5:
    has_velocity_limits: true
    max_velocity: 10.29744
    has_acceleration_limits: true
    max_acceleration: 2.05949
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.471975
    has_acceleration_limits: true
    max_acceleration: 2.094395